# Site settings
title:       M.ichael.co.uk
author:      Michael Cook
description: "Michael Cook's Projects and Assorted Whatnots"
baseurl:     ""
url:         "http://m.ichael.co.uk"
timezone:    Europe/London
# include: .htaccess (not included by default)
exclude:     ["*.bat", "README_*", "NOTE_*", "node_modules", "gemfile", "Gemfile.lock", "bower_components", "*.sh"]
#keep_files:  ["_assets/images"]

# Stop publishing of future-dated posts
future: false

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  false

# Social
github: entozoon
twitter: entozoon
linkedin: michaelmorgancook
email: michael@m.ichael.co.uk

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
excerpt_separator: <!--readmore-->
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
pagination:
  limit: false
  per_page: 2

sass:
#  style: compressed
  style: nested
gems:
 - 'jekyll-sitemap'
 - 'jekyll-press'

assets:
  cache: true
  # put checksum onto filenames. alternative is 'none'.
  # prevents local cache as well as hotlinking and access to original image
  cachebust: hard
  js_compressor:  uglifier
  css_compressor: sass

#assets:
#  prefix: "/_assets"
#  assets:
#    - "*.jpg"
#  digest: true
#  sources:
#    - "_assets/stylesheets"
#    - "_assets/javascripts"
#    - "_assets/images"
#    - "_assets/img"
