# Site settings
title:       M.ichael.co.uk
author:      Michael Cook
description: "Michael Cook's Projects and Assorted Whatnots"
baseurl:     ""
url:         "http://m.ichael.co.uk"
timezone:    Europe/London

# Files to go into _site
# include: .htaccess (if ever needed, not included by default)
exclude:     ["*.bat", "README_*", "NOTE_*", "node_modules", "gemfile", "Gemfile.lock", "bower_components", "*.sh", "*.example"]

# Social
github: entozoon
twitter: entozoon
linkedin: michaelmorgancook
email: michael@m.ichael.co.uk

# Build settings
excerpt_separator: <!--readmore-->
#markdown: kramdown
#redcarpet:
  #extensions: ['smart', 'tables', 'with_toc_data', 'hard_wrap']

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
permalink: /:categories/:title.html

# Stop publishing of future-dated posts
future: false

sass:
#  style: compressed
  style: nested
gems:
 - 'jekyll-press'

assets:
  compress:
    css: true
    js: true
#  cache: false | directory | default: .asset-cache
  cache: .asset-cache
#  cdn: https://cdn.example.com
#  skip_baseurl_with_cdn: false
#   skip_prefix_with_cdn: false
#  prefix: "/assets"
  assets:
#    - "*.png"
    - "site.css"
  digest: false
  sources:
#    - _assets/css
#    - _assets/images
    - _assets/img
    - _assets/js
    - _assets/stylesheets
#    - _assets/javascripts
#    - _assets/fonts
#  features:
#    automatic_img_size: true | false | default: true
#    automatic_img_alt : true | false | default: true