# Site settings
title:       M.ichael.co.uk
email:       michael@m.ichael.co.uk
author:      Michael Cook
description: "Michael Cook's Projects and Assorted Whatnots"
baseurl:     ""
url:         "http://m.ichael.co.uk"
timezone:    Europe/London
# include: .htaccess (not included by default)
exclude:     ["*.bat", "README_*", "node_modules", "Rakefile"]
#keep_files:

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  false

# Disqus post comments
disqus_shortname:

# Social icons
github_username: entozoon
stackoverflow_id:
twitter_username: entozoon
google_plus_id:
linkedin_username: michaelmorgancook
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  style: compressed
gems: ['jekyll-sitemap']

assets:
  js_compressor:  uglifier
  css_compressor: sass
  cachebust: hard
  cache: false

#assets:
#  prefix: "/_assets"
#  assets:
#    - "*.jpg"
#  digest: true
#  sources:
#    - "_assets/stylesheets"
#    - "_assets/javascripts"
#    - "_assets/images"
#    - "_assets/img"