# Site settings
title:       M.ichael.co.uk
author:      Michael Cook
description: "Michael Cook's Projects and Assorted Whatnots"
baseurl:     ""
url:         "http://m.ichael.co.uk"
timezone:    Europe/London
encoding:    UTF-8

# Files to go into _site
# include: .htaccess (if ever needed, not included by default)
exclude:     ["*.bat", "README_*", "NOTE_*", "node_modules", "gemfile", "Gemfile.lock", "bower_components", "*.sh", "*.example"]

# Social
github: entozoon
twitter: entozoon
linkedin: michaelmorgancook
email: michael@m.ichael.co.uk

# Build settings
excerpt_separator: <!--readmore-->
#markdown: kramdown
#redcarpet:
  #extensions: ['smart', 'tables', 'with_toc_data', 'hard_wrap']

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
  smart_quotes: ["apos", "apos", "quot", "quot"]
permalink: /:categories/:title/

# Stop publishing of future-dated posts
future: false

# Comments
comments: true

sass:
#  style: compressed
  style: nested


#jekyll-press:
#  exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
#  js_options: {}      # js minifier options
#  css_options: {}     # css minifier options
#  html_options: {}    # html minifier options

# (temporarily?) removing jekyll-press as it doesn't compile posts properly, issue queried:
# https://github.com/stereobooster/jekyll-press/issues/25
#gems:
#  - octopress-minify-html
#html_press:
#  unquoted_attributes: false
#  drop_empty_values: false
#  strip_crlf: false
#  js_minifier_options: false
# Update: Can't get this working either, trying to go down the compress.html route
compress_html:
  #clippings: [div, p, ul, td, h1, h2]
  clippings: all # fully clip all whitespace around elements, yolo right?
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

assets:
  compress:
    css: true
    js: true
#  cache: false | directory | default: .asset-cache
  cache: .asset-cache
#  cdn: https://cdn.example.com
#  skip_baseurl_with_cdn: false
#   skip_prefix_with_cdn: false
#  prefix: "/assets"
  assets:
#    - "*.png"
    - "site.css"
  digest: false
  sources:
#    - _assets/css
#    - _assets/images
    - _assets/img
    - _assets/js
    - _assets/stylesheets
#    - _assets/javascripts
#    - _assets/fonts
#  features:
#    automatic_img_size: true | false | default: true
#    automatic_img_alt : true | false | default: true
